name: _
publish_to: "none"

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  bloc: ^8.1.4
  get_it_injector:
  equatable: ^2.0.7

dev_dependencies:
  _application:
    path: packages/application
  _data:
    path: packages/data
  _domain:
    path: packages/domain
  _typedef:
    path: packages/type_def
  build_runner: ^2.4.7
  get_it: ^7.6.6
  get_it_injector_gen:
  lints: ^5.1.1
  test: ^1.24.9
