name: _
publish_to: 'none'

environment:
    sdk: '>=2.17.0 <4.0.0'

dependencies:
    bloc: ^8.1.2
    get_it_injector:
    equatable: ^2.0.5

dev_dependencies:
    _application:
        path: packages/application
    _data:
        path: packages/data
    _domain:
        path: packages/domain
    build_runner: ^2.4.7
    derry: ^1.5.0
    get_it: ^7.6.6
    get_it_injector_gen:
    lints: ^3.0.0
    test: ^1.24.9
    very_good_cli: ^0.19.1

scripts:
    test:
        - dart run build_runner build --delete-conflicting-outputs
        - dart run test
