name: get_it_injector_core
description: Core package for get_it_injector_gen
version: 0.1.0

environment:
    sdk: '>=3.0.0 <4.0.0'

dependencies:
    autoequal: '>0.0.1 <1.0.0'
    get_it_injector: '>=0.0.1 <1.0.0'
    equatable: '>=2.0.0 <3.0.0'
    json_annotation: ^4.8.1

dev_dependencies:
    autoequal_gen: ^0.8.0
    build_runner: ^2.4.7
    derry: ^1.5.0
    json_serializable: ^6.7.1

dependency_overrides:
    get_it_injector:
        git:
            url: https://github.com/Couchsurfing/dart-get-it-injector
            path: get_it_injector

scripts: ../scripts.yaml
